#!/usr/bin/env bash
set -e

if ! type -p go >/dev/null; then
  echo "Go not found on the system" >&2
  exit 1
fi

if [ ! -d "./legitify" ]; then
    echo "Initializing legitify..."
    git clone --depth 1 https://github.com/Legit-Labs/legitify.git &>/dev/null
fi

# Default values
REPO_NAME=""
SCORECARD=""
ORG_NAME=""

# Parse command line arguments
while [[ $# -gt 0 ]]; do
  key="$1"

  case $key in
    --repo)
      REPO_NAME="$2"
      shift
      shift
      ;;
    --scorecard)
      SCORECARD="$2"
      shift
      shift
      ;;
    --org)
      ORG_NAME="$2"
      shift
      shift
      ;;
    *)
      echo "Error: Unknown option: $key"
      exit 1
      ;;
  esac
done

# Build parameter string
PARAMS=""
if [ -n "$REPO_NAME" ]; then
  PARAMS="$PARAMS --repo=$REPO_NAME"
fi
if [ -n "$SCORECARD" ]; then
  PARAMS="$PARAMS --scorecard=$SCORECARD"
fi
if [ -n "$ORG_NAME" ]; then
  PARAMS="$PARAMS --org=$ORG_NAME"
fi

# Run legitify with the provided parameters
cd legitify; LEGITIFY_TOKEN=$(gh auth token) go run ./... analyze --namespace repository $PARAMS; cd ..
